### ISSUE TITLE
Scam site

### ISSUE THREAD

**Issue by p6thos** [AHOHNMYC/chromeosflex#1]
WebOfTrust considers the linked website harmful, pls try to make this website cosidered secure. thx :)

**Comment by AHOHNMYC** [comment]
Sorry, but IDK how to do it :) WoT doesn't allow registration using temp mail, so I can't register there.
Honestly, I don't want to deal with some big corporations like WoT or AV that doesn't respond on claims about false positive or anything else which I cannot control.

Also you may check site by your own: sources are in this repo. And I say more: all links are going to Google. I left jsons untouched, just wrote minimum viable GUI for 'em.

**Comment by p6thos** [comment]
Okay that's no problem, but maybe it's a problem on my end too :)

AHOHNMYC ***@***.***> schrieb am Fr., 6. Mai 2022, 07:37:
